channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- pytorch
- ipykernel
- matplotlib
- pandas
- pyyaml
- scipy
- tqdm
- joblib
- scikit-learn
- scikit-image
- pip:
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.13.1
  - aiosignal==1.4.0
  - anyio==4.11.0
  - argon2-cffi==25.1.0
  - argon2-cffi-bindings==25.1.0
  - arrow==1.4.0
  - attrs==25.4.0
  - beautifulsoup4==4.14.2
  - bleach==6.2.0
  - certifi==2025.10.5
  - cffi==2.0.0
  - charset-normalizer==3.4.4
  - cmcrameri==1.9
  - cmocean==4.0.3
  - colorcet==3.1.0
  - defusedxml==0.7.1
  - fastjsonschema==2.21.2
  - fqdn==1.5.1
  - frozenlist==1.8.0
  - git-filter-repo==2.47.0
  - idna==3.11
  - iniconfig==2.3.0
  - ipywidgets==8.1.7
  - isoduration==20.11.0
  - jsonpointer==3.0.0
  - jsonschema==4.25.1
  - jsonschema-specifications==2025.9.1
  - jupyter-events==0.12.0
  - jupyter_server==2.17.0
  - jupyter_server_proxy==4.4.0
  - jupyter_server_terminals==0.5.3
  - jupyterlab_pygments==0.3.0
  - jupyterlab_widgets==3.0.15
  - lark==1.3.0
  - markdown-it-py==4.0.0
  - matplotlib==3.10.7
  - mdurl==0.1.2
  - meshio==5.3.5
  - mistune==3.1.4
  - more-itertools==10.8.0
  - msgpack==1.1.2
  - multidict==6.7.0
  - munkres==1.1.4
  - nbclient==0.10.2
  - nbconvert==7.16.6
  - nbformat==5.10.4
  - overrides==7.7.0
  - pandocfilters==1.5.1
  - pgcore==1.5.3.post1
  - pluggy==1.6.0
  - pooch==1.8.2
  - prometheus_client==0.23.1
  - propcache==0.4.1
  - pycparser==2.23
  - pygimli==1.5.4
  - PySide6==6.9.0
  - pytest==8.4.2
  - python-json-logger==4.0.0
  - pyvista==0.46.3
  - PyWavelets==1.9.0
  - pywinpty==3.0.2
  - referencing==0.37.0
  - requests==2.32.5
  - rfc3339-validator==0.1.4
  - rfc3986-validator==0.1.1
  - rfc3987-syntax==1.1.0
  - rich==14.2.0
  - rpds-py==0.27.1
  - scooby==0.10.2
  - Send2Trash==1.8.3
  - shiboken6==6.9.0
  - simpervisor==1.0.0
  - sniffio==1.3.1
  - soupsieve==2.8
  - terminado==0.18.1
  - tetgen==0.6.7
  - tinycss2==1.4.0
  - trame==3.12.0
  - trame-client==3.11.2
  - trame-common==1.0.1
  - trame-server==3.6.3
  - trame-vtk==2.10.0
  - trame-vuetify==3.1.0
  - uri-template==1.3.0
  - urllib3==2.5.0
  - vtk==9.5.2
  - webcolors==24.11.1
  - webencodings==0.5.1
  - websocket-client==1.9.0
  - widgetsnbextension==4.0.14
  - wslink==2.4.0
  - yarl==1.22.0
name: gpr-ert
