
# Minimal config to generate 32-electrode Wenner data and run an inversion image
out: ./outputs_wenner

inputs:
  pca: data/interim/pca/pca_joint.joblib
  Z:   data/interim/pca/Z.npz

selection:
  n_fields: 1
  field_offset: 0

geom:
  nz_full: 100
  nx_full: 400
  n_elec: 32
  dx_elec: 1.0
  margin: 3.0
  mesh_area: 0.1
  world_Lx: 31.0

design:
  type: wenner
  wenner_a_min: 1
  wenner_a_max: 10

forward:
  mode: 2d
  noise_rel: 0.02

misc:
  seed: 0

output:
  invert: true
  invert_max_fields: 1
  invert_out: ./outputs_wenner/inversion.png
